routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/about', 'HomeController@about');
Route::get('/contact', 'HomeController@contact');
Route::get('/courses_all', 'HomeController@courses');
Route::get('/detail/{id}', 'HomeController@detail');
Route::get('/payment/{id}', 'HomeController@payment')->middleware('auth');
Route::post('/checkout', 'HomeController@checkout')->middleware('auth');

Auth::routes();

// route admin 
Route::get('/dashboard', function() {
    return view('pages.admin.dashboard');
})->middleware(['auth','admin']);
Route::resource('category', 'CategoryController')->middleware(['auth','admin']);
Route::resource('course', 'CourseController')->middleware(['auth','admin']);
Route::get('bookings', 'BookingController@index')->middleware(['auth','admin']);

app/Course.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function booking()
    {
        return $this->hasMany(Booking::class);
    }
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Course;
use Illuminate\Http\Request;
use File;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courses = Course::all();

        return view('pages.admin.course.index', [
            'courses' => $courses
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('pages.admin.course.create', [
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required',
            'price' => 'required',
            'category_id' => 'required',
            'description' => 'required',
            'thumbnail' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $imageName = time().'.'.$request->thumbnail->extension();  
        $request->thumbnail->move(public_path('images'), $imageName);
        $data['thumbnail'] = $imageName;

        Course::create($data);

        return redirect()->route('course.index')->with('success', 'Course Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Course  $course
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Course  $course
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $course = Course::find($id);
        $categories = Category::all();

        return view('pages.admin.course.edit', [
            'course' => $course,
            'categories' => $categories
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Course  $course
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'name' => 'required',
            'price' => 'required',
            'category_id' => 'required',
            'description' => 'required',
            'thumbnail' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $course = Course::find($id);

        if ($request->has('thumbnail')) {
            $path = 'images/';
            File::delete($path, $course->thumbnail);

            $imageName = time().'.'.$request->thumbnail->extension();  
            $request->thumbnail->move(public_path('images'), $imageName);
            $course->thumbnail = $imageName;
        }

        $course->name = $request->name;
        $course->price = $request->price;
        $course->description = $request->description;
        $course->category_id = $request->category_id;
        $course->save();

        return redirect()->route('course.index')->with('success', 'Course Berhasil Dihapus');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Course  $course
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $course = Course::find($id);
        $course->delete();

        return redirect()->route('course.index')->with('success', 'Course Berhasil Dihapus');
    }
}

resources/views/pages/admin/course/create.blade.php
@extends('layouts.admin')

@section('title', 'Tambah Course')

@section('content')
<form action="{{ route('course.store') }}" method="post" enctype="multipart/form-data">
	@csrf
	<div class="form-group">
		<label>Nama Course</label>
		<input type="text" class="form-control" name="name" placeholder="Masukan Nama">
		@error('name')
			<small class="text-danger">{{ $message }}</small>
		@enderror
	</div>
	<div class="form-group">
		<label>Thumbnail</label>
		<input type="file" class="form-control" name="thumbnail">
		@error('thumbnail')
			<small class="text-danger">{{ $message }}</small>
		@enderror
	</div>
	<div class="form-group">
		<label>Harga</label>
		<input type="number" class="form-control" name="price" placeholder="Masukan Harga">
		@error('price')
			<small class="text-danger">{{ $message }}</small>
		@enderror
	</div>
	<div class="form-group">
		<label for="">Kategory</label>
		<select name="category_id" id="" class="form-control">
			@foreach ($categories as $category)
				<option value="{{ $category->id }}">{{ $category->name }}</option>
			@endforeach
		</select>
	</div>
	<div class="form-group">
		<label for="desc" class="form-label">Keterangan</label>
		<input id="x" type="hidden" name="description">
		<trix-editor input="x"></trix-editor>
		@error('description')
			<small class="text-red">{{ $message }}</small>
		@enderror
	</div>
	<button type="submit" class="btn btn-success mt-2">Simpan</button>
</form>
@endsection

resources/views/pages/admin/course/edit.blade.php
@extends('layouts.admin')

@section('title', 'Tambah Course')

@section('content')
<form action="{{ route('course.update', $course->id) }}" method="post" enctype="multipart/form-data">
	@method('put')
	@csrf
	<div class="form-group">
		<label>Nama Course</label>
		<input type="text" class="form-control" name="name" placeholder="Masukan Nama" value="{{ $course->name }}">
		@error('name')
			<small class="text-danger">{{ $message }}</small>
		@enderror
	</div>
	<div class="form-group">
		<label>Thumbnail</label>
		<input type="file" class="form-control" name="thumbnail">
		@error('thumbnail')
			<small class="text-danger">{{ $message }}</small>
		@enderror
	</div>
	<div class="form-group">
		<label>Harga</label>
		<input type="number" class="form-control" name="price" placeholder="Masukan Harga" value="{{ $course->price }}">
		@error('price')
			<small class="text-danger">{{ $message }}</small>
		@enderror
	</div>
	<div class="form-group">
		<label for="">Kategory</label>
		<select name="category_id" id="" class="form-control">
			@foreach ($categories as $category)
				<option value="{{ $category->id }}">{{ $category->name }}</option>
			@endforeach
		</select>
	</div>
	<div class="form-group">
		<label for="desc" class="form-label">Keterangan</label>
		<input id="x" type="hidden" name="description" value="{{ $course->description }}">
		<trix-editor input="x"></trix-editor>
		@error('description')
			<small class="text-red">{{ $message }}</small>
		@enderror
	</div>
	<button type="submit" class="btn btn-success mt-2">Simpan</button>
</form>
@endsection

resources/views/pages/admin/course/index.blade.php
@extends('layouts.admin')

@section('title', 'Daftar Course')

@section('content')
<a href="{{ route('course.create') }}" class="btn btn-success btn-sm mb-2">Tambah Data</a>
<table id="example1" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Nama Course</th>
      <th>Thumbnail</th>
      <th>Kategory</th>
      <th>Harga</th>
      <th>Aksi</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($courses as $course)
    <tr>
      <td>{{ $course->name }}</td>
      <td width="20%"><img width="100%" src="{{ asset('images/'.$course->thumbnail) }}" alt=""></td>
      <td>{{ $course->category->name }}</td>
      <td>Rp. {{ number_format($course->price) }}</td>
      <td>
        <a href="/course/{{$course->id}}/edit" class="btn btn-primary btn-sm">Edit</a>
        <form onclick="return confirm('yakin ingin hapus?')" action="/course/{{$course->id}}" class="d-inline" method="post">
          @csrf
          @method('DELETE')
          <input type="submit" class="btn btn-danger btn-sm my-1" value="Delete">
        </form>
      </td>
    @endforeach
  </tr>
  </tbody>
  <tbody>
  	
  </tbody>
</table>
@endsection

@push('script')
  <script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
  <script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
  <script>
    $(function () {
      $("#example1").DataTable();
    });

    @if(Session::has('success'))
      Swal.fire({
        title: "Berhasil!",
        text: "{{ session('success') }}",
        icon: "success",
      });
    @endif
  </script>
@endpush